[package]
name = "scalar"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
nanoid = "0.4.0"
scalar-derive = { version = "0.1.0", path = "../scalar-derive" }
serde = { version = "1", features = ["derive"] }
ts-rs = "9"

[dev-dependencies]
serde_json = "1"

