[package]
name = "scalar"
version = "0.1.0"
edition = "2021"

[dependencies]
scalar-derive = { version = "0.1.0", path = "../scalar-derive" }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
serde_json = "1"

