[package]
name = "scalar-axum"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
axum-macros = "0.4.1"
paste = "1.0.15"
scalar = { version = "0.1.0", path = "../scalar" }
serde = "1"
serde_json = "1"

[dev-dependencies]
scalar-surreal = { path = "../scalar-surreal" }
surrealdb = { version = "2.1.2", default-features = false, features = ["kv-surrealkv", "protocol-ws"] }
tokio = { version = "1.38.0", features = ["rt-multi-thread", "fs"] }
tower-http = { version = "0.5.2", features = ["cors"] }
